export const boardbookData = [
  { school_name: "100-297 HS Grant", index: "3184", leaid: "0" },
  { school_name: "A+ Charter Schools", index: "2823", leaid: "0" },
  { school_name: "Ada Public Schools", index: "ada", leaid: "0" },
  { school_name: "Ada-Borup-West School District", index: "2497", leaid: "0" },
  { school_name: "Addison Public Library", index: "2676", leaid: "0" },
  { school_name: "AESA", index: "AESA", leaid: "0" },
  { school_name: "Agar-Blunt-Onida School District", index: "ABO", leaid: "0" },
  { school_name: "Ainsworth Community Schools", index: "415", leaid: "0" },
  { school_name: "Alamo Colleges District", index: "679", leaid: "0" },
  { school_name: "Alanson Public School", index: "2674", leaid: "0" },
  { school_name: "Alex Public Schools", index: "226", leaid: "0" },
  { school_name: "Alexander Public Schools", index: "2682", leaid: "0" },
  { school_name: "Alice ISD", index: "868", leaid: "0" },
  { school_name: "Allen Community College", index: "2650", leaid: "0" },
  { school_name: "Allen Independent School District", index: "855", leaid: "0" },
  { school_name: "Alpena-Montmorency-Alcona ESD", index: "2701", leaid: "0" },
  { school_name: "Alsea Charter School", index: "2548", leaid: "0" },
  { school_name: "Altoona-Midway USD 387", index: "3042", leaid: "0" },
  { school_name: "Alvarado ISD", index: "724", leaid: "0" },
  { school_name: "Amboy CUSD #272", index: "1276", leaid: "0" },
  { school_name: "Anadarko Public Schools", index: "Anadarko", leaid: "0" },
  { school_name: "Anahuac Independent School District", index: "1870", leaid: "0" },
  { school_name: "Anderson-Shiro CISD", index: "633", leaid: "0" },
  { school_name: "Anoka-Hennepin School District 11", index: "2720", leaid: "0" },
  { school_name: "Ansley Public School", index: "Ansley", leaid: "0" },
  { school_name: "Arapahoe-Holbrook Public Schools", index: "418", leaid: "0" },
  { school_name: "Archer City ISD", index: "2988", leaid: "0" },
  { school_name: "Argyle ISD", index: "1395", leaid: "0" },
  { school_name: "Ashland-Greenwood Public Schools", index: "79", leaid: "0" },
  { school_name: "Ashley Community Schools", index: "2751", leaid: "0" },
  { school_name: "Athens Independent School District", index: "635", leaid: "0" },
  { school_name: "Austin Peay State University", index: "597", leaid: "0" },
  { school_name: "Austin Public Schools", index: "2516", leaid: "0" },
  { school_name: "Avery ISD", index: "761", leaid: "0" },
  { school_name: "Baird ISD", index: "2000", leaid: "0" },
  { school_name: "Bakken Area Skills Center", index: "2989", leaid: "0" },
  { school_name: "Baldwin Community Schools", index: "2632", leaid: "0" },
  { school_name: "Banks School District", index: "2613", leaid: "0" },
  { school_name: "Bannockburn School District 106", index: "1248", leaid: "0" },
  { school_name: "Barbers Hill Independent School District", index: "1110", leaid: "0" },
  { school_name: "Barnesville Public Schools", index: "1533", leaid: "0" },
  { school_name: "Bath Community Schools", index: "3210", leaid: "0" },
  { school_name: "Battle Creek Public Schools", index: "2646", leaid: "0" },
  { school_name: "Bay-Arenac ISD", index: "909", leaid: "0" },
  { school_name: "Beaumont ISD", index: "748", leaid: "0" },
  { school_name: "Beaverton School District", index: "1443", leaid: "0" },
  { school_name: "Beeville ISD", index: "2183", leaid: "0" },
  { school_name: "Belcourt School District #7", index: "2815", leaid: "0" },
  { school_name: "Beloit Schools USD 273", index: "2730", leaid: "0" },
  { school_name: "Ben Bolt - Palito Blanco ISD", index: "2197", leaid: "0" },
  { school_name: "Bend-La Pine Schools", index: "2413", leaid: "0" },
  { school_name: "Bennington Public Schools", index: "bennington", leaid: "0" },
  { school_name: "Benzie Central Schools", index: "2367", leaid: "0" },
  { school_name: "Berryhill Public Schools", index: "2981", leaid: "0" },
  { school_name: "Bertrand Community School", index: "182", leaid: "0" },
  { school_name: "Bethany Public Schools", index: "2725", leaid: "0" },
  { school_name: "Bethel Board of Education", index: "2425", leaid: "0" },
  { school_name: "Bishop", index: "3203", leaid: "0" },
  { school_name: "Blachly School District", index: "2514", leaid: "0" },
  { school_name: "Bloomfield Community Schools", index: "424", leaid: "0" },
  { school_name: "Bloomfield Public Schools", index: "2463", leaid: "0" },
  { school_name: "Bloomingdale Public Schools", index: "3205", leaid: "0" },
  { school_name: "Blue Hill Community Schools", index: "423", leaid: "0" },
  { school_name: "Bluff Dale ISD", index: "2721", leaid: "0" },
  { school_name: "Boise City Public Schools", index: "BoiseCity", leaid: "0" },
  { school_name: "BOLD Public Schools", index: "3004", leaid: "0" },
  { school_name: "Bonham ISD", index: "866", leaid: "0" },
  { school_name: "Borger ISD", index: "904", leaid: "0" },
  { school_name: "Boyne City Public Schools", index: "965", leaid: "0" },
  { school_name: "Breckenridge ISD", index: "1647", leaid: "0" },
  { school_name: "Bridge City Independent School District", index: "905", leaid: "0" },
  { school_name: "Bridge Creek Public Schools", index: "530", leaid: "0" },
  { school_name: "Bridgeport ISD", index: "647", leaid: "0" },
  { school_name: "Bridgeport Public Schools", index: "2756", leaid: "0" },
  { school_name: "Bridgman Public Schools", index: "1060", leaid: "0" },
  { school_name: "Brighton Area Schools", index: "2615", leaid: "0" },
  { school_name: "Bristol Public Schools", index: "2447", leaid: "0" },
  { school_name: "Brock ISD", index: "803", leaid: "0" },
  { school_name: "Brownfield ISD", index: "674", leaid: "0" },
  { school_name: "Brush School District", index: "3188", leaid: "0" },
  { school_name: "Buckholts Independent School District", index: "2350", leaid: "0" },
  { school_name: "Buckley Schools", index: "2599", leaid: "0" },
  { school_name: "Buena Vista ISD", index: "712", leaid: "0" },
  { school_name: "Buffalo ISD", index: "2545", leaid: "0" },
  { school_name: "Burlington USD #244", index: "3199", leaid: "0" },
  { school_name: "BURNET CONSOLIDATED I.S.D.", index: "1041", leaid: "0" },
  { school_name: "Burnham School District 154.5", index: "2694", leaid: "0" },
  { school_name: "Burton ISD", index: "2593", leaid: "0" },
  { school_name: "Byron Center Public Schools", index: "930", leaid: "0" },
  { school_name: "C.O.O.R. Intermediate School District", index: "1970", leaid: "0" },
  { school_name: "Caddo Mills ISD", index: "669", leaid: "0" },
  { school_name: "Calallen ISD", index: "934", leaid: "0" },
  { school_name: "Caldwell ISD", index: "680", leaid: "0" },
  { school_name: "Calhoun Intermediate School District", index: "Calhoun", leaid: "0" },
  { school_name: "Callaway Public Schools", index: "callaway", leaid: "0" },
  { school_name: "Callisburg ISD", index: "2750", leaid: "0" },
  { school_name: "Cambridge-Isanti Schools", index: "1122", leaid: "0" },
  { school_name: "Canutillo ISD", index: "864", leaid: "0" },
  { school_name: "Canyon ISD", index: "788", leaid: "0" },
  { school_name: "Carrollton Public Schools", index: "2522", leaid: "0" },
  { school_name: "Carrollton-Farmers Branch ISD", index: "631", leaid: "0" },
  { school_name: "CASB Test School District", index: "3084", leaid: "0" },
  { school_name: "Cascade School District #5", index: "1572", leaid: "0" },
  { school_name: "Cass City Public Schools", index: "2996", leaid: "0" },
  { school_name: "Cedar Hill ISD", index: "1600", leaid: "0" },
  { school_name: "Cedar Mountain Schools - District 2754", index: "2796", leaid: "0" },
  { school_name: "Central Appraisal District of Taylor County", index: "3190", leaid: "0" },
  { school_name: "Central Arizona Valley Institute of Technology", index: "1801", leaid: "0" },
  { school_name: "Central Community College", index: "CCC", leaid: "0" },
  { school_name: "Central CUSD 301", index: "1311", leaid: "0" },
  { school_name: "Central High Public Schools", index: "2176", leaid: "0" },
  { school_name: "Central Public Schools", index: "2403", leaid: "0" },
  { school_name: "Central School District 104", index: "1243", leaid: "0" },
  { school_name: "Century School District 100", index: "2790", leaid: "0" },
  { school_name: "Charlevoix-Emmet ISD", index: "2499", leaid: "0" },
  { school_name: "Chatham School District", index: "2647", leaid: "0" },
  { school_name: "Cheatham County Board of Education", index: "cheathamcountyschools", leaid: "0" },
  { school_name: "Cheboygan Area Schools", index: "3215", leaid: "0" },
  { school_name: "Chester ISD", index: "2687", leaid: "0" },
  { school_name: "Cheylin USD 103", index: "2572", leaid: "0" },
  { school_name: "Chickasha Public Schools", index: "1910", leaid: "0" },
  { school_name: "Chugach School District", index: "2598", leaid: "0" },
  { school_name: "Cimarron Public School", index: "2553", leaid: "0" },
  { school_name: "City of Auburn", index: "2737", leaid: "0" },
  { school_name: "City of Bennet", index: "2724", leaid: "0" },
  { school_name: "City of Blair", index: "Blair", leaid: "0" },
  { school_name: "City of Blue Hill", index: "bluehill", leaid: "0" },
  { school_name: "City of Chadron", index: "2736", leaid: "0" },
  { school_name: "City of Columbus", index: "171", leaid: "0" },
  { school_name: "City of David City", index: "1969", leaid: "0" },
  { school_name: "City of Fort Calhoun", index: "fortcalhoun", leaid: "0" },
  { school_name: "City of Franklin", index: "Franklin", leaid: "0" },
  { school_name: "City of Friend", index: "Friend", leaid: "0" },
  { school_name: "City of Friona", index: "2824", leaid: "0" },
  { school_name: "City of Hayden", index: "2366", leaid: "0" },
  { school_name: "City of Hermantown", index: "2639", leaid: "0" },
  { school_name: "City of Imperial", index: "Imperial", leaid: "0" },
  { school_name: "City of Karnes City", index: "3006", leaid: "0" },
  { school_name: "City of Madison", index: "2570", leaid: "0" },
  { school_name: "City of Ouray", index: "2503", leaid: "0" },
  { school_name: "City of Seward", index: "Seward", leaid: "0" },
  { school_name: "City of Valley", index: "2360", leaid: "0" },
  { school_name: "City of Wahoo", index: "citywahoo", leaid: "0" },
  { school_name: "City of Wakefield", index: "2560", leaid: "0" },
  { school_name: "City of Wakefield", index: "Wakefield", leaid: "0" },
  { school_name: "City of Watford", index: "2633", leaid: "0" },
  { school_name: "City of Waverly", index: "Waverly", leaid: "0" },
  { school_name: "City School District", index: "581", leaid: "0" },
  { school_name: "Clarksville ISD", index: "731", leaid: "0" },
  { school_name: "Cleburne Independent School District", index: "1684", leaid: "0" },
  { school_name: "Cleveland Public School", index: "2475", leaid: "0" },
  { school_name: "Climax-Scotts Community Schools", index: "2506", leaid: "0" },
  { school_name: "Clinton Community Schools", index: "3191", leaid: "0" },
  { school_name: "Clinton County RESA", index: "2714", leaid: "0" },
  { school_name: "Clinton Public Schools", index: "2467", leaid: "0" },
  { school_name: "Clinton Public Schools", index: "Clinton", leaid: "0" },
  { school_name: "Cloud County Community College", index: "2656", leaid: "0" },
  { school_name: "Coastal Bend College", index: "2027", leaid: "0" },
  { school_name: "College of Lake County", index: "2575", leaid: "0" },
  { school_name: "Collinsville CUSD #10", index: "1231", leaid: "0" },
  { school_name: "Colorado Association of School Boards", index: "3185", leaid: "0" },
  { school_name: "Comfort ISD", index: "652", leaid: "0" },
  { school_name: "Community Consolidated School District 59", index: "2677", leaid: "0" },
  { school_name: "Community Consolidated School District 93", index: "1266", leaid: "0" },
  { school_name: "Community High School District 94", index: "1499", leaid: "0" },
  { school_name: "Comstock Public Schools", index: "1037", leaid: "0" },
  { school_name: "Concept Schools - Horizon Science Academy Twin Cities", index: "2626", leaid: "0" },
  { school_name: "Concept Schools - Minnesota Math and Science Academy", index: "2355", leaid: "0" },
  { school_name: "Conestoga Public Schools", index: "435", leaid: "0" },
  { school_name: "Constantine Public Schools", index: "2392", leaid: "0" },
  { school_name: "Copper Country ISD", index: "2693", leaid: "0" },
  { school_name: "Copperas Cove Independent School District", index: "665", leaid: "0" },
  { school_name: "Corbett School District", index: "1554", leaid: "0" },
  { school_name: "Cordova School District", index: "2046", leaid: "0" },
  { school_name: "Corsicana Independent School District", index: "642", leaid: "0" },
  { school_name: "Corvallis School District 509J", index: "1216", leaid: "0" },
  { school_name: "Cotulla ISD", index: "638", leaid: "0" },
  { school_name: "County School District", index: "582", leaid: "0" },
  { school_name: "County School District 2", index: "618", leaid: "0" },
  { school_name: "County School District 3", index: "2596", leaid: "0" },
  { school_name: "County School District TEST", index: "2722", leaid: "0" },
  { school_name: "Coupland Independent School District", index: "2708", leaid: "0" },
  { school_name: "Coventry Board of Education", index: "2424", leaid: "0" },
  { school_name: "Crane Independent School District", index: "2491", leaid: "0" },
  { school_name: "Crawford ISD", index: "2983", leaid: "0" },
  { school_name: "Creek Valley Public Schools", index: "438", leaid: "0" },
  { school_name: "Creighton Public Schools", index: "436", leaid: "0" },
  { school_name: "Crescent Public Schools", index: "2691", leaid: "0" },
  { school_name: "Crete Public Schools", index: "439", leaid: "0" },
  { school_name: "Crook County School District", index: "1863", leaid: "0" },
  { school_name: "Cross Plains ISD", index: "2668", leaid: "0" },
  { school_name: "Crowell ISD", index: "655", leaid: "0" },
  { school_name: "Crystal City Independent School District", index: "1587", leaid: "0" },
  { school_name: "Cumberland County Schools", index: "536", leaid: "0" },
  { school_name: "Cunningham - West Kingman County USD 332", index: "2709", leaid: "0" },
  { school_name: "Cushing Public Schools", index: "2496", leaid: "0" },
  { school_name: "Dale Public Schools", index: "2686", leaid: "0" },
  { school_name: "Dallas School District", index: "2353", leaid: "0" },
  { school_name: "Darion Test", index: "1366", leaid: "0" },
  { school_name: "Darlington Community School District", index: "1581", leaid: "0" },
  { school_name: "Davis Public Schools", index: "355", leaid: "0" },
  { school_name: "Davis School District", index: "914", leaid: "0" },
  { school_name: "Dawson-Boyd Public Schools", index: "2573", leaid: "0" },
  { school_name: "Dayton Independent School District", index: "639", leaid: "0" },
  { school_name: "Decatur ISD", index: "648", leaid: "0" },
  { school_name: "Deer Creek Public Schools", index: "2818", leaid: "0" },
  { school_name: "Deer River Schools ISD 317", index: "2476", leaid: "0" },
  { school_name: "Deerfield Public School District 109", index: "1747", leaid: "0" },
  { school_name: "Demo - Harper College", index: "3209", leaid: "0" },
  { school_name: "Demo - Litchfield Community District 12", index: "2625", leaid: "0" },
  { school_name: "Denton ISD", index: "949", leaid: "0" },
  { school_name: "Derby Public Schools", index: "2426", leaid: "0" },
  { school_name: "Detroit Lakes Public Schools", index: "2364", leaid: "0" },
  { school_name: "Devers ISD", index: "745", leaid: "0" },
  { school_name: "Dime Box ISD", index: "773", leaid: "0" },
  { school_name: "Divide ISD", index: "2485", leaid: "0" },
  { school_name: "Document Only Test #2", index: "1382", leaid: "0" },
  { school_name: "Document Only Test School", index: "1143", leaid: "0" },
  { school_name: "Dolores County School District RE-2J", index: "3192", leaid: "0" },
  { school_name: "Dolton School District 149", index: "2571", leaid: "0" },
  { school_name: "Douglas County West Community School", index: "114", leaid: "0" },
  { school_name: "Douglas School District 51-1", index: "douglas", leaid: "0" },
  { school_name: "DRIPPING SPRINGS INDEPENDENT SCHOOL DISTRICT", index: "634", leaid: "0" },
  { school_name: "Drumright Public Schools", index: "2614", leaid: "0" },
  { school_name: "Duluth Public Schools", index: "963", leaid: "0" },
  { school_name: "East Aurora School District 131", index: "1665", leaid: "0" },
  { school_name: "East China School District", index: "2609", leaid: "0" },
  { school_name: "East Lansing Public Schools", index: "1629", leaid: "0" },
  { school_name: "East Mississippi Community College", index: "2651", leaid: "0" },
  { school_name: "Eastern Oklahoma County Technology Center", index: "3186", leaid: "0" },
  { school_name: "Eastern Upper Peninsula Intermediate School District", index: "2786", leaid: "0" },
  { school_name: "Ector County Independent School District", index: "1406", leaid: "0" },
  { school_name: "Ector ISD", index: "2492", leaid: "0" },
  { school_name: "Eddyville Charter School", index: "2821", leaid: "0" },
  { school_name: "Edgewood ISD-Bexar County", index: "844", leaid: "0" },
  { school_name: "Edgewood ISD-Van Zandt County", index: "1298", leaid: "0" },
  { school_name: "Edina Public Schools", index: "2636", leaid: "0" },
  { school_name: "Education Service Center, Region 20", index: "1988", leaid: "0" },
  { school_name: "El Campo Independent School District", index: "901", leaid: "0" },
  { school_name: "Elba Public Schools", index: "441", leaid: "0" },
  { school_name: "Electra Independent School District", index: "2552", leaid: "0" },
  { school_name: "Elizabethton City Schools", index: "594", leaid: "0" },
  { school_name: "Elk Rapids Schools", index: "2387", leaid: "0" },
  { school_name: "Elkhart ISD", index: "1307", leaid: "0" },
  { school_name: "Elkhorn Valley Schools", index: "408", leaid: "0" },
  { school_name: "Elysian Fields ISD", index: "2644", leaid: "0" },
  { school_name: "Emerson-Hubbard Public Schools", index: "Emerson-Hubbard", leaid: "0" },
  { school_name: "Empire Public Schools", index: "2494", leaid: "0" },
  { school_name: "Enid Public Schools", index: "Enid", leaid: "0" },
  { school_name: "Ennis ISD", index: "862", leaid: "0" },
  { school_name: "Epic Charter School", index: "2685", leaid: "0" },
  { school_name: "ESU 01", index: "467", leaid: "0" },
  { school_name: "ESU 06", index: "471", leaid: "0" },
  { school_name: "ESU 08", index: "379", leaid: "0" },
  { school_name: "ESU 13", index: "469", leaid: "0" },
  { school_name: "ESU 16", index: "374", leaid: "0" },
  { school_name: "Eufaula Public Schools", index: "2637", leaid: "0" },
  { school_name: "Eugene School District 4J", index: "1549", leaid: "0" },
  { school_name: "Eureka USD 389", index: "2660", leaid: "0" },
  { school_name: "Eustace ISD", index: "722", leaid: "0" },
  { school_name: "Evanston/Skokie School District 65", index: "1247", leaid: "0" },
  { school_name: "Faith Family Academy", index: "2407", leaid: "0" },
  { school_name: "Fern Ridge SD 28J", index: "1535", leaid: "0" },
  { school_name: "First 5 LA", index: "2038", leaid: "0" },
  { school_name: "First 5 Riverside", index: "2119", leaid: "0" },
  { school_name: "Flinthills USD 492", index: "2603", leaid: "0" },
  { school_name: "Flour Bluff Independent School District", index: "1439", leaid: "0" },
  { school_name: "Forest Grove School District", index: "3194", leaid: "0" },
  { school_name: "Forney ISD", index: "637", leaid: "0" },
  { school_name: "Fort Elliott CISD", index: "2803", leaid: "0" },
  { school_name: "Fort Gibson Public Schools", index: "fortgibson", leaid: "0" },
  { school_name: "Fort Worth ISD", index: "733", leaid: "0" },
  { school_name: "Fredericksburg ISD", index: "825", leaid: "0" },
  { school_name: "Freeman Public Schools", index: "197", leaid: "0" },
  { school_name: "Friends Board of Trustees", index: "533", leaid: "0" },
  { school_name: "Frontier Public Schools", index: "2471", leaid: "0" },
  { school_name: "Fruitport Community Schools", index: "2482", leaid: "0" },
  { school_name: "Gail Borden Public Library District", index: "1426", leaid: "0" },
  { school_name: "Galena City School District", index: "2586", leaid: "0" },
  { school_name: "Galveston Independent School District", index: "1941", leaid: "0" },
  { school_name: "Gans Public School", index: "2717", leaid: "0" },
  { school_name: "Garber Public Schools", index: "2541", leaid: "0" },
  { school_name: "Garden City Public Schools USD 457", index: "2712", leaid: "0" },
  { school_name: "Garland Independent School District", index: "1084", leaid: "0" },
  { school_name: "Garner ISD", index: "730", leaid: "0" },
  { school_name: "Garrison ISD", index: "2055", leaid: "0" },
  { school_name: "Gatesville ISD", index: "910", leaid: "0" },
  { school_name: "Gaylord Community Schools", index: "913", leaid: "0" },
  { school_name: "Geneva CUSD 304", index: "1667", leaid: "0" },
  { school_name: "Gering Public Schools", index: "gering", leaid: "0" },
  { school_name: "Germantown Municipal School District", index: "557", leaid: "0" },
  { school_name: "Giddings ISD", index: "710", leaid: "0" },
  { school_name: "Giltner Public Schools", index: "386", leaid: "0" },
  { school_name: "Glastonbury Public Schools", index: "2417", leaid: "0" },
  { school_name: "Glen Ellyn School District 41", index: "1309", leaid: "0" },
  { school_name: "Gogebic Ontonagon Intermediate School District", index: "2747", leaid: "0" },
  { school_name: "Goliad ISD", index: "2600", leaid: "0" },
  { school_name: "Goodhue County Education District", index: "971", leaid: "0" },
  { school_name: "Goodwell Public Schools", index: "2533", leaid: "0" },
  { school_name: "Goodwill Central Texas/Excel", index: "2502", leaid: "0" },
  { school_name: "Gordon-Rushville School", index: "385", leaid: "0" },
  { school_name: "GPM Life Insurance", index: "2393", leaid: "0" },
  { school_name: "Granby Public Schools", index: "2427", leaid: "0" },
  { school_name: "Grand View Public Schools", index: "3129", leaid: "0" },
  { school_name: "Grandfalls-Royalty Independent School District", index: "3189", leaid: "0" },
  { school_name: "Grandfield Public Schools", index: "2508", leaid: "0" },
  { school_name: "Grandville Public Schools", index: "3041", leaid: "0" },
  { school_name: "Granite School District", index: "2744", leaid: "0" },
  { school_name: "Granton Area School District", index: "2168", leaid: "0" },
  { school_name: "Grape Creek ISD", index: "734", leaid: "0" },
  { school_name: "Grapevine-Colleyville ISD", index: "1198", leaid: "0" },
  { school_name: "Gratiot County Courthouse", index: "1371", leaid: "0" },
  { school_name: "Grayslake CHSD 127", index: "1736", leaid: "0" },
  { school_name: "Greater Albany School District 8J", index: "2005", leaid: "0" },
  { school_name: "Greeneville City Schools", index: "gcschools", leaid: "0" },
  { school_name: "Gresham-Barlow School District", index: "3214", leaid: "0" },
  { school_name: "Gull Lake Community Schools", index: "1057", leaid: "0" },
  { school_name: "Gustine ISD", index: "2784", leaid: "0" },
  { school_name: "Hamilton Community Schools", index: "1630", leaid: "0" },
  { school_name: "Hamilton County Department of Education", index: "571", leaid: "0" },
  { school_name: "Hancock County School District", index: "2645", leaid: "0" },
  { school_name: "Harlem Consolidated School District", index: "1725", leaid: "0" },
  { school_name: "Haskell CISD", index: "2723", leaid: "0" },
  { school_name: "Hearne ISD", index: "2705", leaid: "0" },
  { school_name: "Heart of Texas Behavioral Health Network", index: "3207", leaid: "0" },
  { school_name: "Hedley Independent School District", index: "2684", leaid: "0" },
  { school_name: "Helix School District", index: "2585", leaid: "0" },
  { school_name: "Help Partner", index: "help", leaid: "0" },
  { school_name: "Hemphill ISD", index: "2578", leaid: "0" },
  { school_name: "Hermantown Community Schools", index: "2711", leaid: "0" },
  { school_name: "Hermiston School District", index: "1544", leaid: "0" },
  { school_name: "Hico ISD", index: "656", leaid: "0" },
  { school_name: "Highland Park ISD- Dallas County", index: "2024", leaid: "0" },
  { school_name: "Hill City School", index: "1074", leaid: "0" },
  { school_name: "Holly Area Schools", index: "1471", leaid: "0" },
  { school_name: "Homer Community School", index: "472", leaid: "0" },
  { school_name: "Hondo Independent School District", index: "640", leaid: "0" },
  { school_name: "House Municipal Schools", index: "2760", leaid: "0" },
  { school_name: "Houston Community College", index: "3045", leaid: "0" },
  { school_name: "Hubbard ISD - Hill County", index: "2013", leaid: "0" },
  { school_name: "Huffman ISD", index: "2641", leaid: "0" },
  { school_name: "Hugo Public Schools", index: "2813", leaid: "0" },
  { school_name: "Huntley Community School District 158", index: "1422", leaid: "0" },
  { school_name: "Hutto ISD", index: "749", leaid: "0" },
  { school_name: "Idabel Public Schools", index: "341", leaid: "0" },
  { school_name: "Iditarod Area School District", index: "2697", leaid: "0" },
  { school_name: "Illinois Eastern Community Colleges", index: "2652", leaid: "0" },
  { school_name: "Independent School District 748", index: "1516", leaid: "0" },
  { school_name: "Interlocal Health Benefits Committee", index: "IHBC", leaid: "0" },
  { school_name: "Iowa Park CISD", index: "2788", leaid: "0" },
  { school_name: "Iron Mountain Public Schools", index: "2749", leaid: "0" },
  { school_name: "Irving Independent School District", index: "828", leaid: "0" },
  { school_name: "ISD #696 - Ely Public Schools", index: "1352", leaid: "0" },
  { school_name: "ISD 279 - Osseo Area Schools", index: "2519", leaid: "0" },
  { school_name: "Itasca School District #10", index: "1744", leaid: "0" },
  { school_name: "Jackson County School District", index: "1999", leaid: "0" },
  { school_name: "Jacksonville School District #117", index: "1241", leaid: "0" },
  { school_name: "Jarrell ISD", index: "1933", leaid: "0" },
  { school_name: "Jesse's Regression Test Organization", index: "2388", leaid: "0" },
  { school_name: "Jones Public Schools", index: "342", leaid: "0" },
  { school_name: "Jonesboro Elementary School District 43", index: "2523", leaid: "0" },
  { school_name: "Joppa - Maple Grove Unit District #38", index: "2825", leaid: "0" },
  { school_name: "Joseph City Unified School District", index: "894", leaid: "0" },
  { school_name: "Judson ISD", index: "1434", leaid: "0" },
  { school_name: "Junction Independent School District", index: "753", leaid: "0" },
  { school_name: "Justus-Tiawah", index: "1943", leaid: "0" },
  { school_name: "Kansas School Board Association", index: "Kansas", leaid: "0" },
  { school_name: "Karnack ISD", index: "3197", leaid: "0" },
  { school_name: "Kaufman Independent School District", index: "2293", leaid: "0" },
  { school_name: "Kearney Public Schools", index: "73", leaid: "0" },
  { school_name: "Keller Independent School District", index: "2320", leaid: "0" },
  { school_name: "Kent ISD", index: "2589", leaid: "0" },
  { school_name: "Kerens Independent School District", index: "897", leaid: "0" },
  { school_name: "Ketchum Public Schools", index: "2577", leaid: "0" },
  { school_name: "Kildeer Countryside School District 96", index: "2806", leaid: "0" },
  { school_name: "Kilgore College Foundation", index: "2538", leaid: "0" },
  { school_name: "Killdeer Public School", index: "2623", leaid: "0" },
  { school_name: "Killeen Independent School District", index: "1051", leaid: "0" },
  { school_name: "Killingly Public Schools", index: "2428", leaid: "0" },
  { school_name: "Kimball Public Schools", index: "388", leaid: "0" },
  { school_name: "King County Library System", index: "2778", leaid: "0" },
  { school_name: "Kingman USD #20", index: "2802", leaid: "0" },
  { school_name: "Kingsley Area Schools", index: "2354", leaid: "0" },
  { school_name: "Kingsport City Schools", index: "kcs", leaid: "0" },
  { school_name: "Kittson Central School District", index: "3193", leaid: "0" },
  { school_name: "Klein Independent School District", index: "921", leaid: "0" },
  { school_name: "Krum ISD", index: "717", leaid: "0" },
  { school_name: "La Porte Independent School District", index: "767", leaid: "0" },
  { school_name: "La Pryor ISD", index: "960", leaid: "0" },
  { school_name: "LaCrosse Public Schools USD 395", index: "2649", leaid: "0" },
  { school_name: "Lafayette School Corporation", index: "1838", leaid: "0" },
  { school_name: "Lake Pend Oreille School District #84", index: "2582", leaid: "0" },
  { school_name: "Lake Travis Independent School District", index: "900", leaid: "0" },
  { school_name: "Lakeland Joint School District No. 272", index: "2129", leaid: "0" },
  { school_name: "Lakeland School System", index: "lakelandk12", leaid: "0" },
  { school_name: "Lakeway MUD", index: "698", leaid: "0" },
  { school_name: "Lakewood Public Schools", index: "902", leaid: "0" },
  { school_name: "Lamar CISD", index: "2273", leaid: "0" },
  { school_name: "Lamesa ISD", index: "686", leaid: "0" },
  { school_name: "Lancaster ISD", index: "743", leaid: "0" },
  { school_name: "Latta Public Schools", index: "2785", leaid: "0" },
  { school_name: "Lawrence-Nelson Public Schools", index: "lawrence-nelson", leaid: "0" },
  { school_name: "Lawton - Fort Sill Chamber", index: "3159", leaid: "0" },
  { school_name: "Lawton Public Schools", index: "328", leaid: "0" },
  { school_name: "Le Sueur-Henderson Public Schools", index: "1666", leaid: "0" },
  { school_name: "Leakey ISD", index: "706", leaid: "0" },
  { school_name: "Leander ISD", index: "795", leaid: "0" },
  { school_name: "Learning Community of Douglas & Sarpy Counties", index: "389", leaid: "0" },
  { school_name: "Lee College", index: "747", leaid: "0" },
  { school_name: "Leland Public School", index: "2817", leaid: "0" },
  { school_name: "Leroy-Gridley USD 245", index: "2648", leaid: "0" },
  { school_name: "Lester Prairie Schools", index: "2562", leaid: "0" },
  { school_name: "Lewis County Schools", index: "2780", leaid: "0" },
  { school_name: "Lewiston-Altura Public Schools", index: "2341", leaid: "0" },
  { school_name: "Lewisville Independent School District", index: "1194", leaid: "0" },
  { school_name: "Leyton Public Schools", index: "495", leaid: "0" },
  { school_name: "Liberty Independent School District", index: "725", leaid: "0" },
  { school_name: "Lincoln County School District", index: "2565", leaid: "0" },
  { school_name: "Lincoln ESD 156", index: "2505", leaid: "0" },
  { school_name: "Linden-Kildare CISD", index: "739", leaid: "0" },
  { school_name: "Lindop School District 92", index: "1578", leaid: "0" },
  { school_name: "Lisle CUSD 202", index: "1795", leaid: "0" },
  { school_name: "Little Falls Community Schools", index: "903", leaid: "0" },
  { school_name: "Llano ISD", index: "681", leaid: "0" },
  { school_name: "Lockhart Independent School District", index: "714", leaid: "0" },
  { school_name: "Lone Oak Independent School District", index: "2315", leaid: "0" },
  { school_name: "Los Alamos Public Schools", index: "2696", leaid: "0" },
  { school_name: "Louisiana  Citizens Property Insurance Corporation", index: "2594", leaid: "0" },
  { school_name: "Lyford CISD", index: "1489", leaid: "0" },
  { school_name: "Lyme-Old Lyme Schools", index: "2421", leaid: "0" },
  { school_name: "Lyon County School District", index: "1027", leaid: "0" },
  { school_name: "Lyons-Decatur Northeast", index: "499", leaid: "0" },
  { school_name: "Madison Public Schools", index: "2416", leaid: "0" },
  { school_name: "Magnolia ISD", index: "793", leaid: "0" },
  { school_name: "Malakoff Independent School District", index: "653", leaid: "0" },
  { school_name: "Manchester City Schools", index: "manchestercitysch", leaid: "0" },
  { school_name: "Manistee Area Public Schools", index: "1636", leaid: "0" },
  { school_name: "Manistee Intermediate School District", index: "1079", leaid: "0" },
  { school_name: "Mansfield ISD", index: "1116", leaid: "0" },
  { school_name: "Marathon ISD", index: "805", leaid: "0" },
  { school_name: "Marengo CHSD 154", index: "2789", leaid: "0" },
  { school_name: "Marietta Public Schools", index: "Marietta", leaid: "0" },
  { school_name: "Marlow Public Schools", index: "2576", leaid: "0" },
  { school_name: "Marquette Alger Regional Educational Service Agency", index: "1137", leaid: "0" },
  { school_name: "Mart ISD", index: "2436", leaid: "0" },
  { school_name: "Mayville Community Schools", index: "2352", leaid: "0" },
  { school_name: "McAllen Independent School District", index: "1045", leaid: "0" },
  { school_name: "McDade ISD", index: "2814", leaid: "0" },
  { school_name: "McLean County Unit District No. 5", index: "1482", leaid: "0" },
  { school_name: "McLean ISD", index: "2654", leaid: "0" },
  { school_name: "Meade School District 46-1", index: "Meade", leaid: "0" },
  { school_name: "Medford School District", index: "1545", leaid: "0" },
  { school_name: "Medina Valley ISD", index: "760", leaid: "0" },
  { school_name: "Melissa ISD", index: "716", leaid: "0" },
  { school_name: "Memphis ISD", index: "847", leaid: "0" },
  { school_name: "Menahga Public School District 821", index: "940", leaid: "0" },
  { school_name: "Mendota CCSD 289", index: "2543", leaid: "0" },
  { school_name: "Mesa County Valley School District  No. 51", index: "2807", leaid: "0" },
  { school_name: "Metamora CCSD 1", index: "2386", leaid: "0" },
  { school_name: "Metlakatla Indian Community", index: "2581", leaid: "0" },
  { school_name: "Metro Technology Centers", index: "2507", leaid: "0" },
  { school_name: "Mid-Del City Public Schools", index: "585", leaid: "0" },
  { school_name: "Middletown Public Schools", index: "2423", leaid: "0" },
  { school_name: "Middletown Public Schools", index: "2634", leaid: "0" },
  { school_name: "Midlothian ISD", index: "1700", leaid: "0" },
  { school_name: "Milam Appraisal District", index: "2998", leaid: "0" },
  { school_name: "Milam County Commissioners Court", index: "3085", leaid: "0" },
  { school_name: "Mill Creek Academy", index: "2800", leaid: "0" },
  { school_name: "Miller Grove ISD", index: "976", leaid: "0" },
  { school_name: "Millington Community Schools", index: "2551", leaid: "0" },
  { school_name: "Minneapolis Public Schools Board of Education", index: "1807", leaid: "0" },
  { school_name: "Minnewaska Area Schools", index: "1335", leaid: "0" },
  { school_name: "Mission Consolidated Independent School District", index: "741", leaid: "0" },
  { school_name: "Mitchell School District", index: "2678", leaid: "0" },
  { school_name: "Moffat Consolidated #2", index: "2793", leaid: "0" },
  { school_name: "Moffat County School District RE 1", index: "2758", leaid: "0" },
  { school_name: "Montevideo Public Schools", index: "2489", leaid: "0" },
  { school_name: "MOREgroup", index: "2782", leaid: "0" },
  { school_name: "Morgan County Schools", index: "540", leaid: "0" },
  { school_name: "Mount Pulaski CUSD #23", index: "2414", leaid: "0" },
  { school_name: "Mt. Pleasant Public Schools", index: "2679", leaid: "0" },
  { school_name: "Mullen Public Schools", index: "393", leaid: "0" },
  { school_name: "Murchison ISD", index: "2231", leaid: "0" },
  { school_name: "Mustang Public Schools", index: "Mustang", leaid: "0" },
  { school_name: "N1 Demo", index: "3196", leaid: "0" },
  { school_name: "Nacogdoches ISD", index: "786", leaid: "0" },
  { school_name: "NASB Staff Meetings", index: "3198", leaid: "0" },
  { school_name: "NASB TEST TEST TEST", index: "589", leaid: "0" },
  { school_name: "Natalia ISD", index: "688", leaid: "0" },
  { school_name: "National School Boards Association", index: "2394", leaid: "0" },
  { school_name: "NDSBA Test Member School DISTRICT", index: "2810", leaid: "0" },
  { school_name: "NE Land", index: "NELand", leaid: "0" },
  { school_name: "New Berlin CUSD # 16", index: "2004", leaid: "0" },
  { school_name: "New Deal ISD", index: "2798", leaid: "0" },
  { school_name: "New Fairfield Public Schools", index: "2415", leaid: "0" },
  { school_name: "New Town Public Schools", index: "2755", leaid: "0" },
  { school_name: "Newtown Public School District", index: "2787", leaid: "0" },
  { school_name: "Nicole Test Organization", index: "nicoletest", leaid: "0" },
  { school_name: "Nicollet Public Schools", index: "1842", leaid: "0" },
  { school_name: "Niles Community Schools", index: "1659", leaid: "0" },
  { school_name: "Niles Township District for Special Education #807", index: "2698", leaid: "0" },
  { school_name: "Ninnekah Public Schools", index: "2546", leaid: "0" },
  { school_name: "Nixon-Smiley CISD", index: "650", leaid: "0" },
  { school_name: "Nome Public Schools", index: "1867", leaid: "0" },
  { school_name: "Norman Public Schools", index: "213", leaid: "0" },
  { school_name: "North Bend Central Public Schools", index: "452", leaid: "0" },
  { school_name: "North Branch Area Public Schools", index: "1686", leaid: "0" },
  { school_name: "North Platte Public Schools", index: "124", leaid: "0" },
  { school_name: "North Shore School District 112", index: "2398", leaid: "0" },
  { school_name: "North Stonington Public Schools", index: "2628", leaid: "0" },
  { school_name: "North Wasco County School District 21", index: "1556", leaid: "0" },
  { school_name: "Northeast Metro 916", index: "2488", leaid: "0" },
  { school_name: "Northeast USD 246", index: "2627", leaid: "0" },
  { school_name: "Northern Valley Schools", index: "2261", leaid: "0" },
  { school_name: "Northside ISD", index: "2695", leaid: "0" },
  { school_name: "Northville Public Schools", index: "1326", leaid: "0" },
  { school_name: "Northwest Arctic Borough School District", index: "1035", leaid: "0" },
  { school_name: "Northwest Education Services", index: "2486", leaid: "0" },
  { school_name: "Northwest Independent School District", index: "1405", leaid: "0" },
  { school_name: "Northwest Kansas ESC 602", index: "3087", leaid: "0" },
  { school_name: "Northwest Technology Center", index: "2630", leaid: "0" },
  { school_name: "Northwestern Illinois Association", index: "1342", leaid: "0" },
  { school_name: "Novi Community School District", index: "2699", leaid: "0" },
  { school_name: "Nowata Public Schools", index: "2746", leaid: "0" },
  { school_name: "Ogden City School District", index: "752", leaid: "0" },
  { school_name: "Okemos Public Schools", index: "2515", leaid: "0" },
  { school_name: "Oklahoma Liquid Asset Pool", index: "OLAP", leaid: "0" },
  { school_name: "Omaha Housing Authority", index: "201", leaid: "0" },
  { school_name: "Omaha Public Schools", index: "120", leaid: "0" },
  { school_name: "Onaga-Havensville-Wheaton USD 322", index: "2706", leaid: "0" },
  { school_name: "O'Neill Public Schools", index: "oneill", leaid: "0" },
  { school_name: "Ontario School District 8C", index: "1188", leaid: "0" },
  { school_name: "Ord Public Schools", index: "Ord", leaid: "0" },
  { school_name: "Oregon Commission on Autism Spectrum Disorder", index: "2155", leaid: "0" },
  { school_name: "Oregon School Boards Association", index: "Oregon", leaid: "0" },
  { school_name: "Osawatomie USD 367", index: "2595", leaid: "0" },
  { school_name: "Osmond Community Schools", index: "481", leaid: "0" },
  { school_name: "OSSBA Demo", index: "240", leaid: "0" },
  { school_name: "OSSBA Employee Benefits", index: "EBP", leaid: "0" },
  { school_name: "Otsego Public Schools", index: "1652", leaid: "0" },
  { school_name: "Ottawa Area Intermediate School District", index: "969", leaid: "0" },
  { school_name: "Oxford Community Schools", index: "1339", leaid: "0" },
  { school_name: "Oxford USD 358", index: "3088", leaid: "0" },
  { school_name: "Palos Heights School District #128", index: "2434", leaid: "0" },
  { school_name: "Pampa Independent School District", index: "2186", leaid: "0" },
  { school_name: "Papillion La Vista Community Schools", index: "papillion-lavista", leaid: "0" },
  { school_name: "Parkrose School District 3", index: "1541", leaid: "0" },
  { school_name: "Parshall School District #3", index: "2216", leaid: "0" },
  { school_name: "Paw Paw CUSD #271", index: "1977", leaid: "0" },
  { school_name: "Pearl River Community College", index: "2531", leaid: "0" },
  { school_name: "Pearsall ISD", index: "632", leaid: "0" },
  { school_name: "Pennfield Schools", index: "2568", leaid: "0" },
  { school_name: "Perkins-Tryon", index: "2675", leaid: "0" },
  { school_name: "Perryton Independent School District", index: "689", leaid: "0" },
  { school_name: "Petrolia CISD", index: "708", leaid: "0" },
  { school_name: "Pewitt CISD", index: "654", leaid: "0" },
  { school_name: "Phoenix-Talent Schools", index: "2579", leaid: "0" },
  { school_name: "Pickford Public Schools", index: "2808", leaid: "0" },
  { school_name: "Pillager School District #116", index: "2530", leaid: "0" },
  { school_name: "Pinckney Community Schools", index: "2564", leaid: "0" },
  { school_name: "Pine River-Backus Schools", index: "2584", leaid: "0" },
  { school_name: "Pine Tree Independent School District", index: "790", leaid: "0" },
  { school_name: "Pineywoods Community Academy", index: "3043", leaid: "0" },
  { school_name: "Platte County", index: "plattecounty", leaid: "0" },
  { school_name: "Pleasantdale School District 107", index: "1289", leaid: "0" },
  { school_name: "Pleasanton Public Schools", index: "401", leaid: "0" },
  { school_name: "Pojoaque Valley School District", index: "1370", leaid: "0" },
  { school_name: "Ponca City Public Schools", index: "531", leaid: "0" },
  { school_name: "Pond Creek-Hunter Public Schools", index: "2716", leaid: "0" },
  { school_name: "Ponder Independent School District", index: "2363", leaid: "0" },
  { school_name: "Pope County", index: "2342", leaid: "0" },
  { school_name: "Port Huron Area School District", index: "943", leaid: "0" },
  { school_name: "Port of Port Arthur", index: "2761", leaid: "0" },
  { school_name: "Portage Public Schools", index: "1485", leaid: "0" },
  { school_name: "Portland Public Schools", index: "915", leaid: "0" },
  { school_name: "Prairie Hills USD 113", index: "2715", leaid: "0" },
  { school_name: "Prairie Lea ISD", index: "2719", leaid: "0" },
  { school_name: "Preston Joint School District #201", index: "2607", leaid: "0" },
  { school_name: "Preston Public Schools", index: "2429", leaid: "0" },
  { school_name: "Proviso Area for Exceptional Children", index: "2812", leaid: "0" },
  { school_name: "Proviso Township High Schools", index: "1791", leaid: "0" },
  { school_name: "Public Schools of Petoskey", index: "1237", leaid: "0" },
  { school_name: "Quitman Independent School District", index: "926", leaid: "0" },
  { school_name: "Rantoul City Schools", index: "2431", leaid: "0" },
  { school_name: "Read Foundation/Memphis School of Excellence", index: "SEMemphis", leaid: "0" },
  { school_name: "Reed City Area Public Schools", index: "2534", leaid: "0" },
  { school_name: "Reedsport School District", index: "2759", leaid: "0" },
  { school_name: "Refugio ISD", index: "2532", leaid: "0" },
  { school_name: "Region 16 Education Service Center", index: "906", leaid: "0" },
  { school_name: "Region 16 PSP Consolidated ISD Advisory Board", index: "2804", leaid: "0" },
  { school_name: "Region 17 Education Service Center", index: "2601", leaid: "0" },
  { school_name: "Region 18 Education Service Center", index: "756", leaid: "0" },
  { school_name: "Region 7 Education Service Center", index: "2710", leaid: "0" },
  { school_name: "Renwick USD 267", index: "2797", leaid: "0" },
  { school_name: "Reynolds School District", index: "1006", leaid: "0" },
  { school_name: "Rhodes School District 84 1/2", index: "2726", leaid: "0" },
  { school_name: "Rice CISD", index: "663", leaid: "0" },
  { school_name: "Richardson ISD", index: "705", leaid: "0" },
  { school_name: "Richland County CUSD 1", index: "1308", leaid: "0" },
  { school_name: "Ridgeview CUSD #19", index: "2404", leaid: "0" },
  { school_name: "Ridgewood High School District 234", index: "2337", leaid: "0" },
  { school_name: "Riley CCSD 18", index: "3005", leaid: "0" },
  { school_name: "Robinson CUSD #2", index: "2513", leaid: "0" },
  { school_name: "Robstown ISD", index: "1504", leaid: "0" },
  { school_name: "Rock Ridge Public Schools - ISD 2909", index: "1613", leaid: "0" },
  { school_name: "Rockford Public Schools", index: "3040", leaid: "0" },
  { school_name: "Rockport-Fulton Independent School District", index: "854", leaid: "0" },
  { school_name: "Ropes Independent School District", index: "2792", leaid: "0" },
  { school_name: "Roscoe Collegiate ISD", index: "2397", leaid: "0" },
  { school_name: "Roseville Area Schools", index: "2473", leaid: "0" },
  { school_name: "Royal Oak Schools", index: "1657", leaid: "0" },
  { school_name: "Royal Valley USD 337", index: "2574", leaid: "0" },
  { school_name: "Ruidoso Municipal School District", index: "801", leaid: "0" },
  { school_name: "Russell Test", index: "604", leaid: "0" },
  { school_name: "Russellville School District", index: "2994", leaid: "0" },
  { school_name: "Saginaw Township Community Schools", index: "1171", leaid: "0" },
  { school_name: "Saline County", index: "507", leaid: "0" },
  { school_name: "Salt Creek School District 48", index: "2680", leaid: "0" },
  { school_name: "Salt Lake City School District", index: "2763", leaid: "0" },
  { school_name: "San Antonio ISD", index: "1982", leaid: "0" },
  { school_name: "San Benito Schools", index: "2809", leaid: "0" },
  { school_name: "San Elizario ISD", index: "2311", leaid: "0" },
  { school_name: "San Felipe Del Rio CISD", index: "775", leaid: "0" },
  { school_name: "San Vicente ISD", index: "2986", leaid: "0" },
  { school_name: "Sandhills Public Schools", index: "sandhills", leaid: "0" },
  { school_name: "Sandy Creek Public Schools", index: "sandycreek", leaid: "0" },
  { school_name: "Sanford-Fritch ISD", index: "693", leaid: "0" },
  { school_name: "Santa Maria Independent School District", index: "3195", leaid: "0" },
  { school_name: "Santo ISD", index: "1128", leaid: "0" },
  { school_name: "Sargent Public Schools", index: "459", leaid: "0" },
  { school_name: "Savoy ISD", index: "2539", leaid: "0" },
  { school_name: "Sayre Public Schools", index: "sayre", leaid: "0" },
  { school_name: "Schleicher County ISD", index: "2739", leaid: "0" },
  { school_name: "Schoolcraft Community Schools", index: "2500", leaid: "0" },
  { school_name: "Scio School District", index: "2820", leaid: "0" },
  { school_name: "Scottsbluff Public Schools", index: "49", leaid: "0" },
  { school_name: "Seaside School District", index: "3046", leaid: "0" },
  { school_name: "Seguin ISD", index: "867", leaid: "0" },
  { school_name: "Selenium UI Test City (Tier 2)", index: "576", leaid: "0" },
  { school_name: "SH 130 Municipal Management District No. 1", index: "2743", leaid: "0" },
  { school_name: "Shawnee Public Schools", index: "356", leaid: "0" },
  { school_name: "Shelton Public Schools", index: "shelton", leaid: "0" },
  { school_name: "Shepherd ISD", index: "673", leaid: "0" },
  { school_name: "Shickley Public Schools", index: "485", leaid: "0" },
  { school_name: "Silsbee Independent School District", index: "667", leaid: "0" },
  { school_name: "Sioux Falls School District 49-5", index: "siouxfalls", leaid: "0" },
  { school_name: "Sitka School District", index: "2528", leaid: "0" },
  { school_name: "Sivells Bend ISD", index: "2653", leaid: "0" },
  { school_name: "Slidell ISD", index: "2602", leaid: "0" },
  { school_name: "Smith Center USD 237", index: "2997", leaid: "0" },
  { school_name: "Smith County Board of Education", index: "smithcoedu", leaid: "0" },
  { school_name: "Socorro ISD", index: "2313", leaid: "0" },
  { school_name: "Solomon Unified School District 393", index: "2984", leaid: "0" },
  { school_name: "Somers Public Schools", index: "2459", leaid: "0" },
  { school_name: "South Harrison Community School Corporation", index: "1138", leaid: "0" },
  { school_name: "South Platte School District 95", index: "402", leaid: "0" },
  { school_name: "South Umpqua School District", index: "2991", leaid: "0" },
  { school_name: "Southeast Technical College", index: "STC", leaid: "0" },
  { school_name: "Southern Oklahoma Technology Center", index: "2638", leaid: "0" },
  { school_name: "Southfield Public Schools", index: "1651", leaid: "0" },
  { school_name: "Southington Public Schools", index: "2466", leaid: "0" },
  { school_name: "Splendora ISD", index: "1602", leaid: "0" },
  { school_name: "Spring Branch Independent School District", index: "889", leaid: "0" },
  { school_name: "Spring Hill ISD", index: "771", leaid: "0" },
  { school_name: "Spring Valley Academy", index: "2738", leaid: "0" },
  { school_name: "Spring Valley CCSD 99", index: "2223", leaid: "0" },
  { school_name: "St. Anthony-New Brighton", index: "2549", leaid: "0" },
  { school_name: "St. Charles Community Schools", index: "1612", leaid: "0" },
  { school_name: "St. Cloud Area School District 742", index: "1478", leaid: "0" },
  { school_name: "St. Johns Public Schools", index: "1654", leaid: "0" },
  { school_name: "St. Joseph County ISD", index: "2188", leaid: "0" },
  { school_name: "St. Mary's Charter School", index: "2535", leaid: "0" },
  { school_name: "Stafford Public Schools", index: "2420", leaid: "0" },
  { school_name: "Standish-Sterling Community Schools", index: "1124", leaid: "0" },
  { school_name: "Stanfield School District", index: "2819", leaid: "0" },
  { school_name: "Stanton Community Schools", index: "405", leaid: "0" },
  { school_name: "Stapleton Public Schools", index: "Stapleton", leaid: "0" },
  { school_name: "Starr County Memorial Hospital", index: "3187", leaid: "0" },
  { school_name: "Stigler Public Schools", index: "624", leaid: "0" },
  { school_name: "Stillwater Area Public Schools", index: "2592", leaid: "0" },
  { school_name: "Stillwater Public Schools", index: "2791", leaid: "0" },
  { school_name: "Strasburg School District 31J", index: "2822", leaid: "0" },
  { school_name: "Summerland Public School", index: "1418", leaid: "0" },
  { school_name: "Sunnybrook School District", index: "2480", leaid: "0" },
  { school_name: "Superior Public Schools", index: "204", leaid: "0" },
  { school_name: "Swartz Creek Community Schools", index: "2437", leaid: "0" },
  { school_name: "Sweeny ISD", index: "630", leaid: "0" },
  { school_name: "Syracuse USD 494", index: "2669", leaid: "0" },
  { school_name: "Syracuse-Dunbar-Avoca Public Schools", index: "461", leaid: "0" },
  { school_name: "Taft ISD", index: "645", leaid: "0" },
  { school_name: "Taylor ISD", index: "2401", leaid: "0" },
  { school_name: "Tazewell-Mason Counties Special Education Association", index: "2704", leaid: "0" },
  { school_name: "Tecumseh Public Schools", index: "2587", leaid: "0" },
  { school_name: "Tejano Center for Community Concerns", index: "2681", leaid: "0" },
  { school_name: "Tennessee School Boards Association", index: "508", leaid: "0" },
  { school_name: "Test City for Texas", index: "577", leaid: "0" },
  { school_name: "Test Manual", index: "1355", leaid: "0" },
  { school_name: "Test Non-School Without Settings", index: "1103", leaid: "0" },
  { school_name: "Test Non-School Without Settings", index: "1104", leaid: "0" },
  { school_name: "Test Regression", index: "2389", leaid: "0" },
  { school_name: "Test School for OSSBA (2)", index: "2620", leaid: "0" },
  { school_name: "Test School for OSSBA (3)", index: "2621", leaid: "0" },
  { school_name: "Test School for OSSBA (4)", index: "2622", leaid: "0" },
  { school_name: "Test School Without Settings", index: "1105", leaid: "0" },
  { school_name: "Test School Without Settings", index: "1102", leaid: "0" },
  { school_name: "tester valley", index: "3182", leaid: "0" },
  { school_name: "Texas Southern University", index: "2066", leaid: "0" },
  { school_name: "Texhoma", index: "3204", leaid: "0" },
  { school_name: "Thayer Central Community Schools", index: "thayercentral", leaid: "0" },
  { school_name: "Thomas-Fay-Custer Public Schools", index: "1978", leaid: "0" },
  { school_name: "Thornton Fractional THSD 215", index: "2702", leaid: "0" },
  { school_name: "Three Rivers Health Department", index: "2658", leaid: "0" },
  { school_name: "Three Way ISD", index: "2673", leaid: "0" },
  { school_name: "Throckmorton Collegiate ISD", index: "2474", leaid: "0" },
  { school_name: "Tioga Independent School District", index: "2805", leaid: "0" },
  { school_name: "to be removed Marengo CHSD 154", index: "2795", leaid: "0" },
  { school_name: "Tonganoxie USD 464", index: "2757", leaid: "0" },
  { school_name: "Town of Benson", index: "1593", leaid: "0" },
  { school_name: "Town of Horizon City", index: "928", leaid: "0" },
  { school_name: "Township High School District 214", index: "2567", leaid: "0" },
  { school_name: "Tri-County Schools", index: "2748", leaid: "0" },
  { school_name: "Udall USD 463", index: "2765", leaid: "0" },
  { school_name: "Umatilla School District", index: "2588", leaid: "0" },
  { school_name: "Umatilla-Morrow Head Start", index: "2544", leaid: "0" },
  { school_name: "Union", index: "3151", leaid: "0" },
  { school_name: "Union City Community Schools", index: "2400", leaid: "0" },
  { school_name: "Union City Public Schools", index: "2215", leaid: "0" },
  { school_name: "Unionville-Sebewaing Area School District", index: "2987", leaid: "0" },
  { school_name: "United ISD", index: "2029", leaid: "0" },
  { school_name: "University of Houston System", index: "685", leaid: "0" },
  { school_name: "USD 333 Concordia Public Schools", index: "2410", leaid: "0" },
  { school_name: "USD 417 - Morris County", index: "2990", leaid: "0" },
  { school_name: "Valley View ISD - Hidalgo County", index: "922", leaid: "0" },
  { school_name: "Van Alstyne ISD", index: "850", leaid: "0" },
  { school_name: "Van Buren ISD", index: "1474", leaid: "0" },
  { school_name: "Van Vleck ISD", index: "742", leaid: "0" },
  { school_name: "Vanguard Academy", index: "2827", leaid: "0" },
  { school_name: "Venus Independent School District", index: "636", leaid: "0" },
  { school_name: "Village of Dorchester", index: "2753", leaid: "0" },
  { school_name: "Village of Kenesaw", index: "2349", leaid: "0" },
  { school_name: "Village of Malcolm", index: "villagemalcolm", leaid: "0" },
  { school_name: "Waconda USD 272", index: "2631", leaid: "0" },
  { school_name: "Wagner Community School", index: "Wagner", leaid: "0" },
  { school_name: "Walled Lake Consolidated School District", index: "927", leaid: "0" },
  { school_name: "Waller ISD", index: "737", leaid: "0" },
  { school_name: "Warren County Board of Education", index: "3213", leaid: "0" },
  { school_name: "Washington Community High School", index: "1590", leaid: "0" },
  { school_name: "Washington County", index: "WashingtonCountyNE", leaid: "0" },
  { school_name: "Washington County School System", index: "918", leaid: "0" },
  { school_name: "Waterville-Elysian-Morristown School District", index: "1222", leaid: "0" },
  { school_name: "Waunakee Community School District", index: "1924", leaid: "0" },
  { school_name: "Wauseon Exempted Village Schools", index: "2794", leaid: "0" },
  { school_name: "Wayne Public Schools", index: "2518", leaid: "0" },
  { school_name: "Waynoka Public Schools", index: "Waynoka", leaid: "0" },
  { school_name: "Wayzata Public Schools", index: "1040", leaid: "0" },
  { school_name: "Webb CISD", index: "2612", leaid: "0" },
  { school_name: "Weeping Water Public Schools", index: "465", leaid: "0" },
  { school_name: "Welch Public Schools", index: "2008", leaid: "0" },
  { school_name: "Wellington USD 353", index: "2642", leaid: "0" },
  { school_name: "Wellston Public Schools", index: "2517", leaid: "0" },
  { school_name: "WESLACO INDEPENDENT SCHOOL DISTRICT", index: "2555", leaid: "0" },
  { school_name: "West Bonner County School District 83", index: "2136", leaid: "0" },
  { school_name: "West Iron Public Schools", index: "2690", leaid: "0" },
  { school_name: "West Linn-Wilsonville School District", index: "1543", leaid: "0" },
  { school_name: "West Ottawa Public Schools", index: "2764", leaid: "0" },
  { school_name: "West Point Public Schools", index: "westpoint", leaid: "0" },
  { school_name: "Western Technology Center", index: "2526", leaid: "0" },
  { school_name: "Westhoff ISD", index: "2828", leaid: "0" },
  { school_name: "Weston Public Schools", index: "2468", leaid: "0" },
  { school_name: "Westville Public Schools", index: "westville", leaid: "0" },
  { school_name: "Wharton ISD", index: "808", leaid: "0" },
  { school_name: "Wichita Falls Independent School District", index: "676", leaid: "0" },
  { school_name: "Willis ISD", index: "2995", leaid: "0" },
  { school_name: "Wilson ISD", index: "2779", leaid: "0" },
  { school_name: "Windom Area Schools", index: "2781", leaid: "0" },
  { school_name: "Windsor Public Schools", index: "2419", leaid: "0" },
  { school_name: "Win-E-Mac Schools", index: "2811", leaid: "0" },
  { school_name: "Winona ISD", index: "925", leaid: "0" },
  { school_name: "Wisner-Pilger Public Schools", index: "173", leaid: "0" },
  { school_name: "Woodbridge School District", index: "2455", leaid: "0" },
  { school_name: "Woodville ISD", index: "769", leaid: "0" },
  { school_name: "Workforce Solutions Alamo", index: "751", leaid: "0" },
  { school_name: "Wrenshall School", index: "2703", leaid: "0" },
  { school_name: "WRUSD", index: "893", leaid: "0" },
  { school_name: "Ysleta Independent School District", index: "2312", leaid: "0" },
  { school_name: "Yukon Flats School District", index: "2391", leaid: "0" },
  { school_name: "Yukon Public Schools", index: "306", leaid: "0" },
  { school_name: "Yutan Public Schools", index: "yutan", leaid: "0" }
];
